services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webapp_network

volumes:
  postgres-data:

networks:
  webapp_network:
    driver: bridge
